# Generated by Django 3.2.2 on 2021-05-10 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_id', models.IntegerField()),
                ('status', models.CharField(choices=[('SUCCESS', 'success'), ('FAILURE', 'failure'), ('PENDING', 'pending')], max_length=7)),
                ('event', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=50)),
                ('before', models.CharField(max_length=40)),
                ('after', models.CharField(max_length=40)),
                ('ref', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=100)),
                ('author_email', models.CharField(max_length=320)),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField()),
            ],
            options={
                'db_table': 'builds',
                'ordering': ('-started',),
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'repos',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'success'), ('FAILURE', 'failure'), ('PENDING', 'pending')], max_length=7)),
                ('ignore_error', models.BooleanField()),
                ('started', models.DateTimeField()),
                ('stopped', models.DateTimeField()),
                ('on_success', models.BooleanField()),
                ('on_failure', models.BooleanField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_pipeline.build')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_pipeline.repo')),
            ],
            options={
                'db_table': 'stages',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'success'), ('FAILURE', 'failure'), ('PENDING', 'pending')], max_length=7)),
                ('exit_code', models.IntegerField()),
                ('started', models.IntegerField()),
                ('stopped', models.IntegerField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_pipeline.stage')),
            ],
            options={
                'db_table': 'steps',
            },
        ),
        migrations.CreateModel(
            name='FetchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fetched', models.BooleanField(default=False)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_pipeline.repo')),
            ],
            options={
                'db_table': 'fetch_jobs',
            },
        ),
        migrations.CreateModel(
            name='FailureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('regexp', models.CharField(max_length=100)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_pipeline.repo')),
            ],
            options={
                'db_table': 'failure_categories',
            },
        ),
        migrations.AddField(
            model_name='build',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_pipeline.repo'),
        ),
    ]
