# Generated by Django 3.2.2 on 2021-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchjob',
            name='fetching',
            field=models.BooleanField(default=False),
        ),
    ]
