# Generated by Django 3.2.2 on 2021-05-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_drone_api', '0002_fetchjob_fetching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='build_id',
            field=models.IntegerField(unique=True),
        ),
    ]
