# Generated by Django 3.2.2 on 2021-05-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_drone_api', '0005_stage_stage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_id',
            field=models.IntegerField(unique=True),
        ),
    ]
