# Generated by Django 3.2.2 on 2021-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_drone_api', '0006_alter_stage_stage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='started',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='stopped',
            field=models.DateTimeField(),
        ),
    ]
