# Generated by Django 3.2.2 on 2021-05-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_drone_api', '0007_auto_20210510_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='deploy_to',
            field=models.CharField(default='stage', max_length=50),
            preserve_default=False,
        ),
    ]
